But what happens if one of the async components fails to retrieve its data? Are we stuck with the loading indicator?

No, the fallback content disappears when all components are resolved, successfully or not. So we end up with just the component in success showing up.

We can catch the potential errors though, by using the <mark style="background: #FF5582A6;">onErrorCaptured</mark> lifecycle hook. onErrorCaptured can be used in a component to capture any error from a descendent component.

You can do whatever you need to handle the error, and return true (or don’t return) to let it propagate up the chain of components, or return false to stop its propagation.

```js
const errorMessage = ref<string | null>(null);
onErrorCaptured((e: unknown) => {
console.warn(e);
errorMessage.value = (e as Error).message;
return false;
});
```

A classic use-case is to then display the error to our user using a v-if:

```js
<div>
<h1>Pony {{ ponyModel.name }}</h1>
<div v-if="errorMessage">An error occurred while loading data: {{ errorMessage
}}</div>
<Suspense>
<div>
<TrackRecord :ponyId="ponyModel.id" />
<BirthCertificate :ponyId="ponyModel.id" />
</div>
<template #fallback>Loading...</template>
</Suspense>
</div>
```

If one of the components fails, the error message will be displayed, and the other component as well. You can of course use a v-else on the Suspense element if you don’t want to display any of the components if one fails.

